### ISSUE TITLE
README.md needs beautification

### ISSUE THREAD

**Issue by 4k5h1t** [Takashi069/autodeck#8]
The readme looks really dry and people wanting to contribute have no way to understand how to start, need to add instructions...

**Comment by gautamk01** [comment]
I would like to work on this.

**Comment by Takashi069** [comment]
@gautamk01 ,
@4k5h1t  had already contacted regarding the issue. If it's alright with him, you can work together. But I doubt, collaborations would be required for a README beautification :sweat_smile:  

Feel free to clone and build the project to find issues. If you do manage to find one, you can raise it in the issues section. 

Steps to build the project are mentioned in Issue #5's comment section. I know it's not an ideal way but that's why we want an improved README in the first place. :smile_cat:

**Comment by Takashi069** [comment]
@4k5h1t Any updates on the README so far ?
